### ISSUE TITLE
Eureka 5.2.1 and RichTextRow issue

### ISSUE THREAD

**Issue by kira6783** [EurekaCommunity/RichTextRow#13]
@fabfelici  : Please look into this , needed urgent pls

i have been developing ios app with Eureka Form and also used RichTextRow

when i add only Eureka it install 5.2.1 pod
but later if i add pod RichTextRow it degraded Eureka to 4.3.1

in Eureka 4.3.1 if i archive the build in xcode 11.5 it has the following issue

for expression at [/Users/iOSProjects/Projects/App/ley/Pods/Eureka/Source/Core/RowType.swift:238:35 - line:238:82] RangeText="{ [unowned self] in  callback(self.cell, self) "

with error: Segmentation fault: 11 (in target 'Eureka' from project 'Pods') in Eureka 4.3.1

**Comment by mats-claassen** [comment]
Fixed in #12. You can use the master branch until a new release has been made

**Comment by fabfelici** [comment]
Released 1.0.4. Let me know if it works for you now, thanks!

**Comment by kira6783** [comment]
Hi,

Thanks Fabio for your support.
Yes it works now.
