### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Eureka" 5.3.2

### ISSUE THREAD

**Issue by Denok137** [EurekaCommunity/RichTextRow#14]
Hi! Fix it please  

[!] CocoaPods could not find compatible versions for pod "Eureka":
  In Podfile:
    Eureka (= 5.3.2)

    RichTextRow (= 1.0.4) was resolved to 1.0.4, which depends on
      Eureka (~> 5.2.1)

**Comment by mats-claassen** [comment]
Hi @Denok137 just created a PR with an update
