### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Eureka":

### ISSUE THREAD

**Issue by Beelal** [EurekaCommunity/RichTextRow#5]
[!] CocoaPods could not find compatible versions for pod "Eureka":
  In snapshot (Podfile.lock):
    Eureka (= 4.1.1, >= 4.0.0)

  In Podfile:
    Eureka

    RichTextRow (from `https://github.com/EurekaCommunity/RichTextRow`) was resolved to 1.0.1, which depends on
      Eureka (= 4.0)

Specs satisfying the `Eureka, Eureka (= 4.1.1, >= 4.0.0), Eureka (= 4.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by fabfelici** [comment]
Hi, it should be fixed with https://github.com/EurekaCommunity/RichTextRow/commit/7032db1e38e86846051104c797b938ba068c3014

Can you confirm please?

**Comment by rizwan95** [comment]
Yes it works fine now.
