### ISSUE TITLE
Not compatible wit swift 4.2

### ISSUE THREAD

**Issue by mk3d** [EurekaCommunity/RichTextRow#8]
Hi, I try to use RichTextRow with latest swift 4.2 and current eureka master, have an issue with pod install or pod update.
All pod dependencies goes to earlier version.
Any idea? Thx.

**Comment by fabfelici** [comment]
I probably have to update this row to be compatible with latest Eureka version. Sorry about that, I'll try to work on it as soon as possible.

**Comment by fabfelici** [comment]
Hey @mk3d I update the repo and now it should be compatible.

**Comment by mk3d** [comment]
Many thanks! Perfect.
